// <auto-generated />
using System;
using MedChart.DataAccessLayer;
using MedChart.DataAccessLayer.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(MedChartContext))]
    [Migration("20210131164459_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MedChart.PocosLayer.BloodWorkPoco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("exam_date");

                    b.Property<decimal>("Hematocrit")
                        .HasColumnType("decimal(6,4)")
                        .HasColumnName("hematocrit");

                    b.Property<decimal>("Hemoglobin")
                        .HasColumnType("decimal(6,4)")
                        .HasColumnName("hemoglobin");

                    b.Property<decimal>("RedBloodCellCountMCPMcL")
                        .HasColumnType("decimal(6,4)")
                        .HasColumnName("red_blood_cell_count_mcpmcl");

                    b.Property<DateTime?>("ResultsDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("results_date");

                    b.Property<decimal>("WhiteBloodCellCountMCPMcL")
                        .HasColumnType("decimal(6,4)")
                        .HasColumnName("white_blood_cell_count_mcpmcl");

                    b.HasKey("Id");

                    b.ToTable("Blood_Work");
                });
#pragma warning restore 612, 618
        }
    }
}
